
drop table Users;

CREATE TABLE USERS (
  ID INT NOT NULL  PRIMARY KEY,
  USERNAME VARCHAR (32) NOT NULL,
  NAME VARCHAR (64) NOT NULL,
  UNIQUE (USERNAME)
) SEGMENT creation IMMEDIATE;

CREATE SEQUENCE sequence_USERNAME ;

select * from Users;